image: node:alpine

test:
  script:
    - npm ci
    - npm test

codequality:
  stage: test
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay
  allow_failure: true
  services:
    - docker:dind
  script:
    - docker pull codeclimate/codeclimate
    - docker run --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate analyze -e nodesecurity -f json > codeclimate.json || true
  artifacts:
    paths: [codeclimate.json]
